### ISSUE TITLE
Error: Digest method not supported

### ISSUE THREAD

**Issue by yspaksoy** [AppacYazilim/zamanejs#36]
![hata](https://github.com/AppacYazilim/zamanejs/assets/141452119/baa5bf9d-c68c-453b-b2c5-f972ed6f96cc)

Error occurred: Error: Digest method not supported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at C:\Users\L13\WebstormProjects\BRNET_DDEX\node_modules\zamanejs\dist\zamane.cjs:196:27
    at new Promise (<anonymous>)
    at Zamane.hashFromString (C:\Users\L13\WebstormProjects\BRNET_DDEX\node_modules\zamanejs\dist\zamane.cjs:195:12)
    at ZdFunc (C:\Users\L13\WebstormProjects\BRNET_DDEX\sys\fuctions\zamane.js:12:35)
    at Layer.handle [as handle_request] (C:\Users\L13\WebstormProjects\BRNET_DDEX\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\L13\WebstormProjects\BRNET_DDEX\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Users\L13\WebstormProjects\BRNET_DDEX\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Users\L13\WebstormProjects\BRNET_DDEX\node_modules\express\lib\router\layer.js:95:5)

Böyle bir hata alıyorum. Yeni V2.0.6 güncellemesi yapmama rağmen. Yardımcı olursanız çok sevinirim.

**Comment by mehmeteminkartal** [comment]
@yspaksoy Merhaba problem windows'ta digest methodlarının farklı işlenmesi yüzünden oluşmuştur. Hata düzeltildi ve testlere farklı node versiyonları ve windows ile çalıştırılması eklenmiştir. 

Hata 2.0.7 versiyonunda giderilmiştir. 

Eğer hala hata alırsanız lütfen bu issue'ı tekrar açabilirsiniz.
